
// ============================================================
// fields.js — All field definitions + validation rules 
// Derived directly from the XL sheet rules
// ============================================================

const DIFFICULTY = { EASY: 'easy', MEDIUM: 'medium', HARD: 'hard' };

// ──────────────────────────────────────────────────────────────
// VALIDATOR FUNCTIONS
// ──────────────────────────────────────────────────────────────
const Validators = {
  email: (v) => /^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$/.test(v.trim()),
  password: (v) => v.length >= 12 && /[A-Z]/.test(v) && /[a-z]/.test(v) && /[0-9]/.test(v) && /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(v),
  firstName: (v) => /^[a-zA-Z][a-zA-Z\s\.]*$/.test(v.trim()) && v.trim().length > 0,
  lastName: (v) => /^[a-zA-Z][a-zA-Z\s\.]*$/.test(v.trim()) && v.trim().length > 0,
  date: (v) => /^\d{2}-\d{2}-\d{4}$/.test(v.trim()) && (() => { const [d,m,y] = v.split('-').map(Number); return d>=1&&d<=31&&m>=1&&m<=12&&y>=1900&&y<=2025; })(),
  birthdate: (v) => /^\d{2}-\d{2}-\d{4}$/.test(v.trim()) && (() => { const [d,m,y] = v.split('-').map(Number); const age = 2026-y; return d>=1&&d<=31&&m>=1&&m<=12&&y>=1900&&y<=2007&&age>=18; })(),
  phone: (v) => /^\+32\s?\d{1,2}\s?\d{3}\s?\d{2}\s?\d{2}$/.test(v.trim()),
  vatBE: (v) => /^BE\d{9,10}$/.test(v.trim().toUpperCase()),
  bankBE: (v) => /^BE\d{14}$/.test(v.trim().toUpperCase().replace(/\s/g,'')),
  gst: (v) => /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[0-9]{1}[A-Z]{1}[0-9A-Z]{1}$/.test(v.trim().toUpperCase()),
  currencyEUR: (v) => /^EUR\s?\d{1,12}(,\d{2})?$/.test(v.trim().toUpperCase()),
  currencyUSD: (v) => /^USD\s?\d{1,12}(\.\d{2})?$/.test(v.trim().toUpperCase()),
  postalCode: (v) => /^[a-zA-Z0-9\s\-]{3,10}$/.test(v.trim()),
  streetName: (v) => v.trim().length >= 2 && /^[a-zA-Z0-9\s\.]+$/.test(v.trim()),
  houseNumber: (v) => v.trim().length >= 1 && /^[a-zA-Z0-9\s\.]+$/.test(v.trim()),
  city: (v) => /^[a-zA-Z\s\.]{2,}$/.test(v.trim()),
  country: (v) => v.trim().length >= 2 && /^[a-zA-Z\s]+$/.test(v.trim()),
  nationality: (v) => /^[a-zA-Z\s]{2,}$/.test(v.trim()),
  title: (v) => ['mr.','mrs.','miss.','ms.','dr.','prof.'].includes(v.trim().toLowerCase()),
  gender: (v) => ['female','male','non-binary','transgender','intersex','genderqueer','prefer not to say'].includes(v.trim().toLowerCase()),
  recaptcha: (v) => v.trim().toUpperCase() === 'HUMAN',
  imageFile: (v) => /\.(png|jpeg|jpg|gif)$/i.test(v.trim()),
  docFile: (v) => /\.(doc|docx|pdf|txt|xlsx|xls|html|csv|odt)$/i.test(v.trim()),
  videoFile: (v) => /\.(mp4|webm|avi)$/i.test(v.trim()),
  audioFile: (v) => /\.(mp3|m4p|aac)$/i.test(v.trim()),
  confirmPassword: (v, ctx) => v === ctx.newPassword,
};

// ──────────────────────────────────────────────────────────────
// ERROR MESSAGE BUILDERS
// ──────────────────────────────────────────────────────────────
function getError(v, field, ctx = {}) {
  if (!v || v.trim() === '') return field.requiredMsg || 'This field is required.';
  return field.invalidMsg || 'Incorrect format.';
}

// ──────────────────────────────────────────────────────────────
// LEVEL DEFINITIONS
// ──────────────────────────────────────────────────────────────
const LEVELS = [
  {
    id: 1,
    title: 'Login to Your Account',
    subtitle: 'Level 1 — Authentication',
    scenario: 'The company portal is locked. You must pass the login form to access your workstation. Security is tight — one slip and the system logs you out.',
    icon: '🔐',
    fields: [
      {
        id: 'email',
        label: 'Email Address',
        type: 'text',
        placeholder: 'e.g. john.doe@company.com',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Format: string@domain.extension\nRegex: ^([a-zA-Z0-9_\\-.]+)@([a-zA-Z0-9_\\-.]+)\\.([a-zA-Z]{2,5})$',
        example: 'john.doe@company.com',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect format. Use: name@domain.com',
        validate: (v) => Validators.email(v),
      },
      {
        id: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Enter your password',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Min 12 chars. Must include: uppercase, lowercase, number, and special character (!@#$...)',
        example: 'AlPhA@96099-45920$',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Password too weak — needs 12+ chars, uppercase, lowercase, number, and special char.',
        validate: (v) => Validators.password(v),
      },
      {
        id: 'recaptcha',
        label: 'reCAPTCHA Verification',
        type: 'text',
        placeholder: 'Type HUMAN to verify',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'This is a simplified reCAPTCHA. Type exactly: HUMAN',
        example: 'HUMAN',
        requiredMsg: 'This field is required.',
        invalidMsg: 'The answer you entered for the CAPTCHA was not correct.',
        validate: (v) => Validators.recaptcha(v),
      },
    ]
  },

  {
    id: 2,
    title: 'Forgot Your Password?',
    subtitle: 'Level 2 — Password Recovery',
    scenario: 'You blanked on your password. The IT department makes you fill a full recovery form — correctly — before they reset anything. No shortcuts.',
    icon: '🔑',
    fields: [
      {
        id: 'email',
        label: 'Email Address',
        type: 'text',
        placeholder: 'e.g. jane.smith@company.com',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Format: string@domain.extension',
        example: 'jane.smith@company.com',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect format. The email address does not match any account.',
        validate: (v) => Validators.email(v),
      },
      {
        id: 'newPassword',
        label: 'New Password',
        type: 'password',
        placeholder: 'Set a strong new password',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Min 12 chars. Mix of uppercase, lowercase, numbers, and special chars.',
        example: 'N3wP@ssw0rd-2026!',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Password too weak — needs 12+ chars, uppercase, lowercase, number, and special char.',
        validate: (v) => Validators.password(v),
        onValidate: (v, ctx) => { ctx.newPassword = v; }
      },
      {
        id: 'confirmPassword',
        label: 'Confirm Password',
        type: 'password',
        placeholder: 'Re-enter your new password',
        difficulty: DIFFICULTY.EASY,
        points: 100,
        hint: 'Must exactly match the New Password you entered above.',
        example: '(same as New Password)',
        requiredMsg: 'This field is required.',
        invalidMsg: "The two password fields didn't match.",
        validate: (v, ctx) => Validators.confirmPassword(v, ctx),
      },
    ]
  },

  {
    id: 3,
    title: 'Register as a New User',
    subtitle: 'Level 3 — Registration',
    scenario: 'A new team member joins the company. You must fill their onboarding registration form. Get it right or HR will send it back stamped REJECTED.',
    icon: '📝',
    fields: [
      {
        id: 'firstName',
        label: 'First Name',
        type: 'text',
        placeholder: 'e.g. Marie',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphabets only. SPACE and Dot (.) are allowed.',
        example: 'Marie',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Only alphabets, spaces, and dots allowed.',
        validate: (v) => Validators.firstName(v),
      },
      {
        id: 'lastName',
        label: 'Last Name',
        type: 'text',
        placeholder: 'e.g. De Smedt',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphabets only. SPACE and Dot (.) are allowed.',
        example: 'De Smedt',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Only alphabets, spaces, and dots allowed.',
        validate: (v) => Validators.lastName(v),
      },
      {
        id: 'email',
        label: 'Email Address',
        type: 'text',
        placeholder: 'e.g. m.desmedt@company.com',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Format: string@domain.extension',
        example: 'm.desmedt@company.com',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect format.',
        validate: (v) => Validators.email(v),
      },
      {
        id: 'recaptcha',
        label: 'reCAPTCHA Verification',
        type: 'text',
        placeholder: 'Type HUMAN to verify',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Simplified CAPTCHA. Type exactly: HUMAN',
        example: 'HUMAN',
        requiredMsg: 'This field is required.',
        invalidMsg: 'The answer you entered for the CAPTCHA was not correct.',
        validate: (v) => Validators.recaptcha(v),
      },
    ]
  },

  {
    id: 4,
    title: 'Complete Your Address',
    subtitle: 'Level 4 — Address Details',
    scenario: 'HR needs your exact Belgian office address for the employee directory. One wrong character and the mail goes to the wrong floor — or the wrong country.',
    icon: '🏢',
    fields: [
      {
        id: 'streetName',
        label: 'Street Name',
        type: 'text',
        placeholder: 'e.g. Rue de la Loi',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphanumeric. SPACE and Dot allowed.',
        example: 'Rue de la Loi',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid street name. Only letters, numbers, spaces, and dots.',
        validate: (v) => Validators.streetName(v),
      },
      {
        id: 'houseNumber',
        label: 'House Number',
        type: 'text',
        placeholder: 'e.g. 16B',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphanumeric. Max 50 characters.',
        example: '16B',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid house number.',
        validate: (v) => Validators.houseNumber(v),
      },
      {
        id: 'postalCode',
        label: 'Postal Code',
        type: 'text',
        placeholder: 'e.g. 1000',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphanumeric. 3–10 characters.',
        example: '1000',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid postal code.',
        validate: (v) => Validators.postalCode(v),
      },
      {
        id: 'city',
        label: 'City',
        type: 'text',
        placeholder: 'e.g. Brussels',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphabets, space, and dot only.',
        example: 'Brussels',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid city name.',
        validate: (v) => Validators.city(v),
      },
      {
        id: 'country',
        label: 'Country',
        type: 'text',
        placeholder: 'e.g. Belgium',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphabets and spaces only.',
        example: 'Belgium',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid country name.',
        validate: (v) => Validators.country(v),
      },
    ]
  },

  {
    id: 5,
    title: 'Set Up Your Profile',
    subtitle: 'Level 5 — Profile Configuration',
    scenario: 'The company intranet profile page awaits. This one gets personal — titles, birthdates, phone numbers, nationality. The system is very strict about Belgian phone format.',
    icon: '👤',
    fields: [
      {
        id: 'title',
        label: 'Title',
        type: 'text',
        placeholder: 'Mr. / Mrs. / Ms. / Dr. / Prof.',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Choose from: Mr. / Mrs. / Miss. / Ms. / Dr. / Prof.',
        example: 'Dr.',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid title. Use: Mr. Mrs. Miss. Ms. Dr. or Prof.',
        validate: (v) => Validators.title(v),
      },
      {
        id: 'gender',
        label: 'Gender',
        type: 'text',
        placeholder: 'e.g. Female / Male / Non-binary',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Options: Female, Male, Non-binary, Transgender, Intersex, Genderqueer, Prefer not to say',
        example: 'Non-binary',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid gender value.',
        validate: (v) => Validators.gender(v),
      },
      {
        id: 'birthdate',
        label: 'Birthdate',
        type: 'text',
        placeholder: 'dd-mm-yyyy (e.g. 15-06-1992)',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Format: dd-mm-yyyy. Must be 18+ years old.',
        example: '15-06-1992',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect date. Use dd-mm-yyyy format. Must be 18+.',
        validate: (v) => Validators.birthdate(v),
      },
      {
        id: 'phone',
        label: 'Phone Number (Belgium)',
        type: 'text',
        placeholder: '+32 3 369 01 68',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Belgium format with country code: +32 followed by local number.\nExample: +32 3 369 01 68',
        example: '+32 3 369 01 68',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Please enter valid Belgian phone. Format: +32 X XXX XX XX',
        validate: (v) => Validators.phone(v),
      },
      {
        id: 'nationality',
        label: 'Nationality',
        type: 'text',
        placeholder: 'e.g. Belgian',
        difficulty: DIFFICULTY.EASY,
        points: 50,
        hint: 'Alphabets and spaces only.',
        example: 'Belgian',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid nationality.',
        validate: (v) => Validators.nationality(v),
      },
    ]
  },

  {
    id: 6,
    title: 'Upload Your Documents',
    subtitle: 'Level 6 — File Submission',
    scenario: "The compliance team needs your files. They are extremely picky about formats. Wrong extension? REJECTED. The pile grows taller with each mistake.",
    icon: '📁',
    fields: [
      {
        id: 'docFile',
        label: 'Document Upload',
        type: 'text',
        placeholder: 'Enter filename (e.g. report.pdf)',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Allowed formats: .doc .docx .pdf .txt .xls .xlsx .html .csv .odt\nMax size: 10MB',
        example: 'annual_report.pdf',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid file format. Please upload only .doc .docx .pdf .txt .xls .xlsx .html .csv .odt',
        validate: (v) => Validators.docFile(v),
      },
      {
        id: 'imageFile',
        label: 'Profile Image Upload',
        type: 'text',
        placeholder: 'Enter image filename (e.g. photo.png)',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Allowed formats: .png .jpeg .jpg .gif\nMax size: 2MB',
        example: 'profile_photo.png',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid file format. Please upload only .png .jpeg .jpg .gif',
        validate: (v) => Validators.imageFile(v),
      },
      {
        id: 'videoFile',
        label: 'Video Upload',
        type: 'text',
        placeholder: 'Enter video filename (e.g. demo.mp4)',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Allowed formats: .mp4 .webm .avi\nMax size: 1GB',
        example: 'company_intro.mp4',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid file format. Please upload only .mp4 .webm .avi',
        validate: (v) => Validators.videoFile(v),
      },
      {
        id: 'audioFile',
        label: 'Audio Upload',
        type: 'text',
        placeholder: 'Enter audio filename (e.g. brief.mp3)',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Allowed formats: .mp3 .m4p .aac\nMax size: 100MB',
        example: 'voicenote.mp3',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid file format. Please upload only .mp3 .m4p .aac',
        validate: (v) => Validators.audioFile(v),
      },
    ]
  },

  {
    id: 7,
    title: 'Payment & Tax Setup',
    subtitle: 'Level 7 — Financial Fields',
    scenario: "Finance. The final frontier. Belgian bank accounts, VAT numbers, and currency formats. One digit wrong and the accountants will bury you — literally.",
    icon: '💳',
    fields: [
      {
        id: 'bankBE',
        label: 'Bank Account Number (Belgium)',
        type: 'text',
        placeholder: 'e.g. BE12345678901234',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Format: BE followed by exactly 14 digits.\nNo spaces.',
        example: 'BE12345678901234',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Bank account must start with BE followed by 14 digits.',
        validate: (v) => Validators.bankBE(v),
      },
      {
        id: 'vatBE',
        label: 'VAT Number (Belgium)',
        type: 'text',
        placeholder: 'e.g. BE0123456789',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Format: BE followed by 9 or 10 digits.',
        example: 'BE0123456789',
        requiredMsg: 'This field is required.',
        invalidMsg: 'VAT must start with BE followed by 9 or 10 digits.',
        validate: (v) => Validators.vatBE(v),
      },
      {
        id: 'currencyEUR',
        label: 'Amount in EUR (European Format)',
        type: 'text',
        placeholder: 'e.g. EUR 1.250,99',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Format: EUR followed by amount. Use comma for decimals.\nExample: EUR 2500,00',
        example: 'EUR 2500,00',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect format. Use: EUR followed by amount (comma for decimals).',
        validate: (v) => Validators.currencyEUR(v),
      },
    ]
  },

  {
    id: 8,
    title: 'The Boss Level',
    subtitle: 'Level 8 — Final Audit',
    scenario: "The Grand Audit. The Big Boss needs EVERYTHING. All your details in one epic combined form. This is the ultimate test. No shortcuts. No mercy.",
    icon: '👾',
    isBoss: true,
    fields: [
      {
        id: 'email',
        label: 'Email Address',
        type: 'text',
        placeholder: 'e.g. john.doe@company.com',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Format: string@domain.extension',
        example: 'john.doe@company.com',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect format.',
        validate: (v) => Validators.email(v),
      },
      {
        id: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Strong password',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Min 12 chars. Uppercase, lowercase, number, special char.',
        example: 'AlPhA@96099-45920$',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Password too weak.',
        validate: (v) => Validators.password(v),
      },
      {
        id: 'phone',
        label: 'Phone (Belgium)',
        type: 'text',
        placeholder: '+32 3 369 01 68',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Belgium format: +32 followed by local number.',
        example: '+32 3 369 01 68',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Invalid Belgian phone. Format: +32 X XXX XX XX',
        validate: (v) => Validators.phone(v),
      },
      {
        id: 'birthdate',
        label: 'Birthdate',
        type: 'text',
        placeholder: 'dd-mm-yyyy',
        difficulty: DIFFICULTY.MEDIUM,
        points: 100,
        hint: 'Format: dd-mm-yyyy. Must be 18+.',
        example: '15-06-1992',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect date. Use dd-mm-yyyy. Must be 18+.',
        validate: (v) => Validators.birthdate(v),
      },
      {
        id: 'vatBE',
        label: 'VAT Number (Belgium)',
        type: 'text',
        placeholder: 'BE + 9 or 10 digits',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Format: BE followed by 9 or 10 digits.',
        example: 'BE0123456789',
        requiredMsg: 'This field is required.',
        invalidMsg: 'VAT must start with BE followed by 9 or 10 digits.',
        validate: (v) => Validators.vatBE(v),
      },
      {
        id: 'gst',
        label: 'GST Number (India)',
        type: 'text',
        placeholder: 'e.g. 27ABCDE1234F1Z5',
        difficulty: DIFFICULTY.HARD,
        points: 200,
        hint: 'Format: 2 digits (state) + 5 letters + 4 digits + letter + digit + letter + alphanumeric\nTotal: 15 characters.',
        example: '27ABCDE1234F1Z5',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Incorrect format. GSTIN must be 15 alphanumeric chars.',
        validate: (v) => Validators.gst(v),
      },
      {
        id: 'bankBE',
        label: 'Bank Account (Belgium)',
        type: 'text',
        placeholder: 'BE + 14 digits',
        difficulty: DIFFICULTY.HARD,
        points: 150,
        hint: 'Format: BE followed by exactly 14 digits.',
        example: 'BE12345678901234',
        requiredMsg: 'This field is required.',
        invalidMsg: 'Bank account must be BE + 14 digits.',
        validate: (v) => Validators.bankBE(v),
      },
    ]
  }
];
